// Definir o tipo Planet localmente
export interface Planet {
  id: string
  name: string
  portuguese_name: string
  radius: number
  mass: number
  gravity: number
  average_temperature: number
  distance_from_sun: number
  orbital_period: number
  rotation_period: number
  description: string
  curiosities: string[]
  image_url: string
  color: string
  moons_count: number
  moons?: Moon[]
  composition: string
  atmosphere: string
  magnetic_field: boolean
  rings: boolean
  axial_tilt: number
  escape_velocity: number
  albedo: number
  created_at: string
  updated_at: string
}

// Definir o tipo Moon
export interface Moon {
  id: string
  name: string
  portuguese_name: string
  radius: number
  mass: number
  gravity: number
  average_temperature: number
  distance_from_planet: number
  orbital_period: number
  rotation_period: number
  description: string
  curiosities: string[]
  image_url: string
  color: string
  composition: string
  atmosphere: string
  magnetic_field: boolean
  axial_tilt: number
  albedo: number
  parent_planet: string
}

// Dados fixos dos planetas do Sistema Solar
export const FIXED_PLANETS: Planet[] = [
  {
    id: "1",
    name: "mercury",
    portuguese_name: "Mercúrio",
    radius: 2439.7,
    mass: 3.3011e23,
    gravity: 3.7,
    average_temperature: 167,
    distance_from_sun: 57910000,
    orbital_period: 88,
    rotation_period: 1407.6,
    description: "O menor planeta do Sistema Solar e o mais próximo do Sol. Não possui atmosfera e tem temperaturas extremas.",
    curiosities: [
      "Não possui atmosfera",
      "Temperaturas extremas entre -173°C e 427°C",
      "Um dia em Mercúrio dura 176 dias terrestres",
      "É o planeta mais rápido do Sistema Solar"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA15190/PIA15190~orig.jpg",
    color: "#8C7853",
    moons_count: 0,
    composition: "70% metais, 30% silicatos",
    atmosphere: "Exosfera tênue de oxigênio, sódio, hidrogênio, hélio e potássio",
    magnetic_field: true,
    rings: false,
    axial_tilt: 0.034,
    escape_velocity: 4.25,
    albedo: 0.119,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "2",
    name: "venus",
    portuguese_name: "Vênus",
    radius: 6051.8,
    mass: 4.8675e24,
    gravity: 8.87,
    average_temperature: 464,
    distance_from_sun: 108200000,
    orbital_period: 225,
    rotation_period: -5832.5,
    description: "O planeta mais quente do Sistema Solar devido ao efeito estufa. Tem uma atmosfera extremamente densa.",
    curiosities: [
      "Rotação retrógrada (gira no sentido contrário)",
      "Atmosfera densa de CO2",
      "Pressão atmosférica 92 vezes maior que a Terra",
      "É o planeta mais brilhante no céu noturno"
    ],
    image_url: "/venus-texture.png",
    color: "#FFC649",
    moons_count: 0,
    composition: "Núcleo de ferro, manto de silicatos, crosta basáltica",
    atmosphere: "96.5% CO2, 3.5% nitrogênio, traços de outros gases",
    magnetic_field: false,
    rings: false,
    axial_tilt: 177.4,
    escape_velocity: 10.36,
    albedo: 0.75,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "3",
    name: "earth",
    portuguese_name: "Terra",
    radius: 6371,
    mass: 5.9724e24,
    gravity: 9.81,
    average_temperature: 15,
    distance_from_sun: 149600000,
    orbital_period: 365.25,
    rotation_period: 24,
    description: "Nosso planeta natal, o único conhecido com vida. Tem uma atmosfera rica em oxigênio e água líquida.",
    curiosities: [
      "71% da superfície é coberta por água",
      "Possui campo magnético protetor",
      "Único planeta conhecido com vida",
      "Tem uma lua que estabiliza seu eixo"
    ],
    image_url: "/earth-planet-texture-blue-green.jpg",
    color: "#6B93D6",
    moons_count: 1,
    composition: "Núcleo de ferro-níquel, manto de silicatos, crosta continental e oceânica",
    atmosphere: "78% nitrogênio, 21% oxigênio, 1% outros gases",
    magnetic_field: true,
    rings: false,
    axial_tilt: 23.44,
    escape_velocity: 11.19,
    albedo: 0.306,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "4",
    name: "mars",
    portuguese_name: "Marte",
    radius: 3389.5,
    mass: 6.4171e23,
    gravity: 3.71,
    average_temperature: -65,
    distance_from_sun: 227900000,
    orbital_period: 687,
    rotation_period: 24.6,
    description: "O Planeta Vermelho, conhecido por sua cor avermelhada devido ao óxido de ferro em sua superfície.",
    curiosities: [
      "Possui as maiores montanhas do Sistema Solar",
      "Evidências de água no passado",
      "Tem duas luas: Fobos e Deimos",
      "Dia marciano é similar ao terrestre (24h 37min)"
    ],
    image_url: "/mars-red-texture.png",
    color: "#CD5C5C",
    moons_count: 2,
    composition: "Núcleo de ferro-sulfeto, manto de silicatos, crosta basáltica",
    atmosphere: "95% CO2, 3% nitrogênio, 2% argônio",
    magnetic_field: false,
    rings: false,
    axial_tilt: 25.19,
    escape_velocity: 5.03,
    albedo: 0.17,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "5",
    name: "jupiter",
    portuguese_name: "Júpiter",
    radius: 69911,
    mass: 1.8982e27,
    gravity: 24.79,
    average_temperature: -110,
    distance_from_sun: 778500000,
    orbital_period: 4333,
    rotation_period: 9.9,
    description: "O maior planeta do Sistema Solar, um gigante gasoso com uma Grande Mancha Vermelha.",
    curiosities: [
      "Grande Mancha Vermelha (tempestade gigante)",
      "Mais de 95 luas conhecidas",
      "Massa maior que todos os outros planetas juntos",
      "Tem um sistema de anéis tênue"
    ],
    image_url: "/jupiter-gas-giant-planet-texture-bands.jpg",
    color: "#D8CA9D",
    moons_count: 95,
    composition: "90% hidrogênio, 10% hélio, traços de outros elementos",
    atmosphere: "89% hidrogênio, 10% hélio, 1% outros gases",
    magnetic_field: true,
    rings: true,
    axial_tilt: 3.13,
    escape_velocity: 59.5,
    albedo: 0.503,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "6",
    name: "saturn",
    portuguese_name: "Saturno",
    radius: 58232,
    mass: 5.6834e26,
    gravity: 10.44,
    average_temperature: -140,
    distance_from_sun: 1432000000,
    orbital_period: 10759,
    rotation_period: 10.7,
    description: "Conhecido por seus anéis espetaculares, é um gigante gasoso com baixa densidade.",
    curiosities: [
      "Anéis espetaculares compostos de gelo e rocha",
      "Menor densidade que a água",
      "Mais de 146 luas conhecidas",
      "Titã é sua maior lua, maior que Mercúrio"
    ],
    image_url: "/saturn-realistic.jpg",
    color: "#FAD5A5",
    moons_count: 146,
    composition: "96% hidrogênio, 3% hélio, 1% outros elementos",
    atmosphere: "96% hidrogênio, 3% hélio, 1% outros gases",
    magnetic_field: true,
    rings: true,
    axial_tilt: 26.73,
    escape_velocity: 35.5,
    albedo: 0.342,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "7",
    name: "uranus",
    portuguese_name: "Urano",
    radius: 25362,
    mass: 8.6810e25,
    gravity: 8.69,
    average_temperature: -195,
    distance_from_sun: 2867000000,
    orbital_period: 30687,
    rotation_period: -17.2,
    description: "Um gigante de gelo que gira de lado, com uma atmosfera rica em metano.",
    curiosities: [
      "Gira de lado (eixo inclinado 98°)",
      "Atmosfera rica em metano",
      "Tem 27 luas conhecidas",
      "É o planeta mais frio do Sistema Solar"
    ],
    image_url: "/uranus-realistic.jpg",
    color: "#4FD0E7",
    moons_count: 27,
    composition: "83% hidrogênio, 15% hélio, 2% metano",
    atmosphere: "83% hidrogênio, 15% hélio, 2% metano",
    magnetic_field: true,
    rings: true,
    axial_tilt: 97.77,
    escape_velocity: 21.3,
    albedo: 0.300,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "8",
    name: "neptune",
    portuguese_name: "Netuno",
    radius: 24622,
    mass: 1.0243e26,
    gravity: 11.15,
    average_temperature: -200,
    distance_from_sun: 4515000000,
    orbital_period: 60190,
    rotation_period: 16.1,
    description: "O planeta mais distante do Sol, um gigante de gelo com ventos extremamente rápidos.",
    curiosities: [
      "Ventos mais rápidos do Sistema Solar (até 2100 km/h)",
      "Tem 14 luas conhecidas",
      "Foi descoberto por cálculos matemáticos",
      "Tritão é sua maior lua com órbita retrógrada"
    ],
    image_url: "/neptune-realistic.jpg",
    color: "#4B70DD",
    moons_count: 14,
    composition: "80% hidrogênio, 19% hélio, 1% metano",
    atmosphere: "80% hidrogênio, 19% hélio, 1% metano",
    magnetic_field: true,
    rings: true,
    axial_tilt: 28.32,
    escape_velocity: 23.5,
    albedo: 0.290,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  }
]

// Função para obter dados de um planeta específico
export function getPlanetByName(name: string): Planet | undefined {
  return FIXED_PLANETS.find(planet => planet.name.toLowerCase() === name.toLowerCase())
}

// Dados das luas principais
export const FIXED_MOONS: Moon[] = [
  // Lua da Terra
  {
    id: "moon-1",
    name: "moon",
    portuguese_name: "Lua",
    radius: 1737.4,
    mass: 7.342e22,
    gravity: 1.62,
    average_temperature: -20,
    distance_from_planet: 384400,
    orbital_period: 27.3,
    rotation_period: 655.7,
    description: "O único satélite natural da Terra, responsável pelas marés e estabilização do eixo terrestre.",
    curiosities: [
      "Sempre mostra a mesma face para a Terra",
      "Está se afastando da Terra 3,8 cm por ano",
      "Tem água congelada nos polos",
      "Formou-se há 4,5 bilhões de anos"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA00302/PIA00302~orig.jpg",
    color: "#C0C0C0",
    composition: "Crosta de anortosito, manto de olivina e piroxênio",
    atmosphere: "Exosfera tênue de hélio, neônio e hidrogênio",
    magnetic_field: false,
    axial_tilt: 6.68,
    albedo: 0.136,
    parent_planet: "earth"
  },
  // Luas de Júpiter (95 luas conhecidas)
  {
    id: "moon-51",
    name: "io",
    portuguese_name: "Io",
    radius: 1821.6,
    mass: 8.93e22,
    gravity: 1.796,
    average_temperature: -143,
    distance_from_planet: 421700,
    orbital_period: 1.77,
    rotation_period: 1.77,
    description: "A lua mais vulcânica do Sistema Solar, com mais de 400 vulcões ativos.",
    curiosities: [
      "Mais de 400 vulcões ativos",
      "Superfície mais jovem do Sistema Solar",
      "Sempre mostra a mesma face para Júpiter",
      "Tem enxofre líquido na superfície"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA00583/PIA00583~orig.jpg",
    color: "#FFFF00",
    composition: "Núcleo rochoso, manto de silicatos, crosta de enxofre",
    atmosphere: "Exosfera tênue de dióxido de enxofre",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.63,
    parent_planet: "jupiter"
  },
  {
    id: "moon-52",
    name: "europa",
    portuguese_name: "Europa",
    radius: 1560.8,
    mass: 4.80e22,
    gravity: 1.315,
    average_temperature: -171,
    distance_from_planet: 671034,
    orbital_period: 3.55,
    rotation_period: 3.55,
    description: "Lua gelada de Júpiter com possível oceano subterrâneo e potencial para vida.",
    curiosities: [
      "Possível oceano líquido subterrâneo",
      "Crosta de gelo de 10-30 km de espessura",
      "Sempre mostra a mesma face para Júpiter",
      "Principal candidata para vida extraterrestre"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA19048/PIA19048~orig.jpg",
    color: "#FFFFFF",
    composition: "Núcleo rochoso, manto de gelo, crosta de gelo de água",
    atmosphere: "Exosfera tênue de oxigênio",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.67,
    parent_planet: "jupiter"
  },
  {
    id: "moon-53",
    name: "ganymede",
    portuguese_name: "Ganimedes",
    radius: 2634.1,
    mass: 1.48e23,
    gravity: 1.428,
    average_temperature: -163,
    distance_from_planet: 1070412,
    orbital_period: 7.15,
    rotation_period: 7.15,
    description: "A maior lua do Sistema Solar, maior que o planeta Mercúrio.",
    curiosities: [
      "Maior lua do Sistema Solar",
      "Maior que o planeta Mercúrio",
      "Única lua com campo magnético próprio",
      "Sempre mostra a mesma face para Júpiter"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA00716/PIA00716~orig.jpg",
    color: "#C0C0C0",
    composition: "Núcleo rochoso, manto de gelo, crosta de gelo e rocha",
    atmosphere: "Exosfera tênue de oxigênio",
    magnetic_field: true,
    axial_tilt: 0,
    albedo: 0.43,
    parent_planet: "jupiter"
  },
  {
    id: "moon-54",
    name: "callisto",
    portuguese_name: "Calisto",
    radius: 2410.3,
    mass: 1.08e23,
    gravity: 1.235,
    average_temperature: -155,
    distance_from_planet: 1882709,
    orbital_period: 16.69,
    rotation_period: 16.69,
    description: "A lua mais externa das quatro principais de Júpiter, com superfície antiga e craterada.",
    curiosities: [
      "Superfície mais antiga do Sistema Solar",
      "Pouco afetada por forças de maré",
      "Sempre mostra a mesma face para Júpiter",
      "Possível oceano subterrâneo"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA01667/PIA01667~orig.jpg",
    color: "#8B7355",
    composition: "Núcleo rochoso, manto de gelo, crosta de gelo e rocha",
    atmosphere: "Exosfera tênue de dióxido de carbono",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.22,
    parent_planet: "jupiter"
  },
  {
    id: "moon-55",
    name: "amalthea",
    portuguese_name: "Amalteia",
    radius: 83.5,
    mass: 2.08e18,
    gravity: 0.020,
    average_temperature: -150,
    distance_from_planet: 181365,
    orbital_period: 0.50,
    rotation_period: 0.50,
    description: "Lua irregular de Júpiter com formato de batata e cor avermelhada.",
    curiosities: [
      "Formato irregular (batata)",
      "Cor avermelhada por enxofre de Io",
      "Sempre mostra a mesma face para Júpiter",
      "Foi descoberta em 1892"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B4513",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.09,
    parent_planet: "jupiter"
  },
  {
    id: "moon-56",
    name: "himalia",
    portuguese_name: "Himalia",
    radius: 85,
    mass: 4.2e18,
    gravity: 0.023,
    average_temperature: -150,
    distance_from_planet: 11440600,
    orbital_period: 250.56,
    rotation_period: 7.78,
    description: "A maior lua irregular de Júpiter, com órbita próxima.",
    curiosities: [
      "Maior lua irregular de Júpiter",
      "Órbita próxima",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 1904"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-57",
    name: "elara",
    portuguese_name: "Elara",
    radius: 43,
    mass: 8.7e17,
    gravity: 0.012,
    average_temperature: -150,
    distance_from_planet: 11741000,
    orbital_period: 259.64,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita próxima.",
    curiosities: [
      "Órbita próxima",
      "Formato irregular",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 1905"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-58",
    name: "pasiphae",
    portuguese_name: "Pasífae",
    radius: 30,
    mass: 3.0e17,
    gravity: 0.008,
    average_temperature: -150,
    distance_from_planet: 23624000,
    orbital_period: 743.63,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 1908"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-59",
    name: "sinope",
    portuguese_name: "Sinope",
    radius: 19,
    mass: 7.5e16,
    gravity: 0.004,
    average_temperature: -150,
    distance_from_planet: 23939000,
    orbital_period: 758.90,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 1914"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-60",
    name: "lysithea",
    portuguese_name: "Lisiteia",
    radius: 18,
    mass: 6.3e16,
    gravity: 0.004,
    average_temperature: -150,
    distance_from_planet: 11717000,
    orbital_period: 259.20,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita próxima.",
    curiosities: [
      "Órbita próxima",
      "Formato irregular",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 1938"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-61",
    name: "carme",
    portuguese_name: "Carme",
    radius: 23,
    mass: 1.3e17,
    gravity: 0.005,
    average_temperature: -150,
    distance_from_planet: 23404000,
    orbital_period: 734.17,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 1938"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-62",
    name: "ananke",
    portuguese_name: "Ananke",
    radius: 14,
    mass: 3.0e16,
    gravity: 0.002,
    average_temperature: -150,
    distance_from_planet: 21276000,
    orbital_period: 610.45,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 1951"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-63",
    name: "leda",
    portuguese_name: "Leda",
    radius: 10,
    mass: 1.1e16,
    gravity: 0.001,
    average_temperature: -150,
    distance_from_planet: 11164000,
    orbital_period: 240.93,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita próxima.",
    curiosities: [
      "Órbita próxima",
      "Formato irregular",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 1974"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-64",
    name: "thebe",
    portuguese_name: "Tebe",
    radius: 49.3,
    mass: 1.5e18,
    gravity: 0.013,
    average_temperature: -150,
    distance_from_planet: 221889,
    orbital_period: 0.67,
    rotation_period: 0.67,
    description: "Lua irregular de Júpiter com órbita próxima.",
    curiosities: [
      "Órbita próxima",
      "Formato irregular",
      "Sempre mostra a mesma face para Júpiter",
      "Foi descoberta em 1979"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-65",
    name: "metis",
    portuguese_name: "Metis",
    radius: 21.5,
    mass: 3.6e16,
    gravity: 0.005,
    average_temperature: -150,
    distance_from_planet: 128852,
    orbital_period: 0.29,
    rotation_period: 0.29,
    description: "A lua mais próxima de Júpiter, com órbita próxima aos anéis.",
    curiosities: [
      "Lua mais próxima de Júpiter",
      "Órbita próxima aos anéis",
      "Sempre mostra a mesma face para Júpiter",
      "Foi descoberta em 1979"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.06,
    parent_planet: "jupiter"
  },
  {
    id: "moon-66",
    name: "adrastea",
    portuguese_name: "Adrasteia",
    radius: 8.2,
    mass: 2.0e15,
    gravity: 0.002,
    average_temperature: -150,
    distance_from_planet: 128971,
    orbital_period: 0.30,
    rotation_period: 0.30,
    description: "Lua pastor de Júpiter, mantém o anel principal.",
    curiosities: [
      "Lua pastor do anel principal",
      "Órbita próxima aos anéis",
      "Sempre mostra a mesma face para Júpiter",
      "Foi descoberta em 1979"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.10,
    parent_planet: "jupiter"
  },
  {
    id: "moon-79",
    name: "themisto",
    portuguese_name: "Temisto",
    radius: 4,
    mass: 6.9e14,
    gravity: 0.0001,
    average_temperature: -150,
    distance_from_planet: 7395000,
    orbital_period: 130.02,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita próxima.",
    curiosities: [
      "Órbita próxima",
      "Formato irregular",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 1975"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-80",
    name: "megaclite",
    portuguese_name: "Megaclite",
    radius: 2.7,
    mass: 2.1e14,
    gravity: 0.0001,
    average_temperature: -150,
    distance_from_planet: 23980000,
    orbital_period: 752.86,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 2000"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-81",
    name: "taygete",
    portuguese_name: "Taigete",
    radius: 2.5,
    mass: 1.6e14,
    gravity: 0.0001,
    average_temperature: -150,
    distance_from_planet: 23360000,
    orbital_period: 732.41,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 2000"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-82",
    name: "chaldene",
    portuguese_name: "Caldene",
    radius: 1.9,
    mass: 7.5e13,
    gravity: 0.00001,
    average_temperature: -150,
    distance_from_planet: 23180000,
    orbital_period: 723.70,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 2000"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-83",
    name: "harpalyke",
    portuguese_name: "Harpalice",
    radius: 2.2,
    mass: 1.2e14,
    gravity: 0.0001,
    average_temperature: -150,
    distance_from_planet: 21105000,
    orbital_period: 623.32,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 2000"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-84",
    name: "kalyke",
    portuguese_name: "Calice",
    radius: 2.6,
    mass: 1.9e14,
    gravity: 0.0001,
    average_temperature: -150,
    distance_from_planet: 23583000,
    orbital_period: 743.05,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 2000"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-85",
    name: "iocaste",
    portuguese_name: "Iocaste",
    radius: 2.6,
    mass: 1.9e14,
    gravity: 0.0001,
    average_temperature: -150,
    distance_from_planet: 21162000,
    orbital_period: 631.60,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 2000"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-86",
    name: "eridome",
    portuguese_name: "Eridome",
    radius: 1.9,
    mass: 7.5e13,
    gravity: 0.00001,
    average_temperature: -150,
    distance_from_planet: 23260000,
    orbital_period: 717.33,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 2000"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-87",
    name: "kallichore",
    portuguese_name: "Calicore",
    radius: 1,
    mass: 4.2e12,
    gravity: 0.000001,
    average_temperature: -150,
    distance_from_planet: 24100000,
    orbital_period: 764.73,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 2003"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-88",
    name: "cyllene",
    portuguese_name: "Cilene",
    radius: 1,
    mass: 4.2e12,
    gravity: 0.000001,
    average_temperature: -150,
    distance_from_planet: 24300000,
    orbital_period: 752.00,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 2003"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-89",
    name: "kore",
    portuguese_name: "Core",
    radius: 1,
    mass: 4.2e12,
    gravity: 0.000001,
    average_temperature: -150,
    distance_from_planet: 24500000,
    orbital_period: 779.17,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 2003"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-90",
    name: "s/2003 j 2",
    portuguese_name: "S/2003 J 2",
    radius: 1,
    mass: 4.2e12,
    gravity: 0.000001,
    average_temperature: -150,
    distance_from_planet: 28500000,
    orbital_period: 982.50,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita muito distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 2003"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-91",
    name: "s/2003 j 3",
    portuguese_name: "S/2003 J 3",
    radius: 1,
    mass: 4.2e12,
    gravity: 0.000001,
    average_temperature: -150,
    distance_from_planet: 20000000,
    orbital_period: 583.88,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 2003"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-92",
    name: "s/2003 j 4",
    portuguese_name: "S/2003 J 4",
    radius: 1,
    mass: 4.2e12,
    gravity: 0.000001,
    average_temperature: -150,
    distance_from_planet: 24000000,
    orbital_period: 755.26,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 2003"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-93",
    name: "s/2003 j 5",
    portuguese_name: "S/2003 J 5",
    radius: 2,
    mass: 3.4e13,
    gravity: 0.00001,
    average_temperature: -150,
    distance_from_planet: 21000000,
    orbital_period: 602.77,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 2003"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-94",
    name: "s/2003 j 9",
    portuguese_name: "S/2003 J 9",
    radius: 1,
    mass: 4.2e12,
    gravity: 0.000001,
    average_temperature: -150,
    distance_from_planet: 23000000,
    orbital_period: 683.02,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 2003"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  {
    id: "moon-95",
    name: "s/2003 j 10",
    portuguese_name: "S/2003 J 10",
    radius: 1,
    mass: 4.2e12,
    gravity: 0.000001,
    average_temperature: -150,
    distance_from_planet: 22000000,
    orbital_period: 634.77,
    rotation_period: 7.78,
    description: "Lua irregular de Júpiter com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita distante de Júpiter",
      "Possível origem em asteroide capturado",
      "Foi descoberta em 2003"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "jupiter"
  },
  // Luas de Marte (2 luas conhecidas)
  {
    id: "moon-2",
    name: "phobos",
    portuguese_name: "Fobos",
    radius: 11.1,
    mass: 1.0659e16,
    gravity: 0.0057,
    average_temperature: -40,
    distance_from_planet: 9376,
    orbital_period: 0.32,
    rotation_period: 0.32,
    description: "A maior e mais próxima lua de Marte, com formato irregular e crateras.",
    curiosities: [
      "Está se aproximando de Marte e será destruída em 50 milhões de anos",
      "Tem uma grande cratera chamada Stickney",
      "É uma das menores luas do Sistema Solar",
      "Sempre mostra a mesma face para Marte"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA10368/PIA10368~orig.jpg",
    color: "#8B7355",
    composition: "Rocha carbonácea com gelo",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.071,
    parent_planet: "mars"
  },
  {
    id: "moon-3",
    name: "deimos",
    portuguese_name: "Deimos",
    radius: 6.2,
    mass: 1.4762e15,
    gravity: 0.003,
    average_temperature: -40,
    distance_from_planet: 23463,
    orbital_period: 1.26,
    rotation_period: 1.26,
    description: "A menor e mais distante lua de Marte, com superfície lisa e crateras.",
    curiosities: [
      "É a menor lua conhecida do Sistema Solar",
      "Tem formato irregular",
      "Sempre mostra a mesma face para Marte",
      "Foi descoberta em 1877"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA10368/PIA10368~orig.jpg",
    color: "#8B7355",
    composition: "Rocha carbonácea com gelo",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.068,
    parent_planet: "mars"
  },
  // Luas de Saturno
  {
    id: "moon-4",
    name: "titan",
    portuguese_name: "Titã",
    radius: 2574,
    mass: 1.3452e23,
    gravity: 1.352,
    average_temperature: -179,
    distance_from_planet: 1221870,
    orbital_period: 15.95,
    rotation_period: 15.95,
    description: "A maior lua de Saturno e segunda maior do Sistema Solar, com atmosfera densa e lagos de hidrocarbonetos.",
    curiosities: [
      "Maior que o planeta Mercúrio",
      "Única lua com atmosfera densa",
      "Tem lagos de metano e etano líquidos",
      "Possui ciclo hidrológico similar ao da Terra"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA09184/PIA09184~orig.jpg",
    color: "#FFA500",
    composition: "Núcleo rochoso, manto de gelo, crosta de gelo e hidrocarbonetos",
    atmosphere: "95% nitrogênio, 5% metano e outros hidrocarbonetos",
    magnetic_field: false,
    axial_tilt: 0.33,
    albedo: 0.22,
    parent_planet: "saturn"
  },
  {
    id: "moon-5",
    name: "enceladus",
    portuguese_name: "Encélado",
    radius: 252.1,
    mass: 1.0802e20,
    gravity: 0.113,
    average_temperature: -201,
    distance_from_planet: 238020,
    orbital_period: 1.37,
    rotation_period: 1.37,
    description: "Uma pequena lua gelada de Saturno com gêiseres de água e possível oceano subterrâneo.",
    curiosities: [
      "Tem gêiseres de água no polo sul",
      "Possível oceano líquido subterrâneo",
      "Uma das superfícies mais refletivas do Sistema Solar",
      "Fonte dos anéis E de Saturno"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA06254/PIA06254~orig.jpg",
    color: "#FFFFFF",
    composition: "Gelo de água com núcleo rochoso",
    atmosphere: "Exosfera tênue de vapor d'água",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.81,
    parent_planet: "saturn"
  },
  {
    id: "moon-10",
    name: "rhea",
    portuguese_name: "Reia",
    radius: 764.3,
    mass: 2.31e21,
    gravity: 0.264,
    average_temperature: -174,
    distance_from_planet: 527108,
    orbital_period: 4.52,
    rotation_period: 4.52,
    description: "A segunda maior lua de Saturno, com superfície craterada e possível oceano subterrâneo.",
    curiosities: [
      "Segunda maior lua de Saturno",
      "Superfície antiga e craterada",
      "Possível oceano líquido subterrâneo",
      "Sempre mostra a mesma face para Saturno"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07763/PIA07763~orig.jpg",
    color: "#C0C0C0",
    composition: "Gelo de água com núcleo rochoso",
    atmosphere: "Exosfera tênue de oxigênio e CO2",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.65,
    parent_planet: "saturn"
  },
  {
    id: "moon-11",
    name: "iapetus",
    portuguese_name: "Jápeto",
    radius: 734.5,
    mass: 1.81e21,
    gravity: 0.223,
    average_temperature: -143,
    distance_from_planet: 3560820,
    orbital_period: 79.33,
    rotation_period: 79.33,
    description: "Lua de Saturno conhecida por sua coloração bicolor e crista equatorial.",
    curiosities: [
      "Superfície bicolor (escura e clara)",
      "Crista equatorial de 20 km de altura",
      "Órbita inclinada e distante",
      "Sempre mostra a mesma face para Saturno"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.05,
    parent_planet: "saturn"
  },
  {
    id: "moon-12",
    name: "dione",
    portuguese_name: "Dione",
    radius: 561.4,
    mass: 1.09e21,
    gravity: 0.232,
    average_temperature: -186,
    distance_from_planet: 377396,
    orbital_period: 2.74,
    rotation_period: 2.74,
    description: "Lua de Saturno com superfície variada e possível atividade geológica.",
    curiosities: [
      "Superfície com vales e cristas",
      "Possível atividade geológica no passado",
      "Sempre mostra a mesma face para Saturno",
      "Tem uma pequena lua co-orbital"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#C0C0C0",
    composition: "Gelo de água com núcleo rochoso",
    atmosphere: "Exosfera tênue de oxigênio",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.60,
    parent_planet: "saturn"
  },
  {
    id: "moon-13",
    name: "tethys",
    portuguese_name: "Tétis",
    radius: 533,
    mass: 6.17e20,
    gravity: 0.145,
    average_temperature: -187,
    distance_from_planet: 294619,
    orbital_period: 1.89,
    rotation_period: 1.89,
    description: "Lua de Saturno com grande cratera e sistema de vales.",
    curiosities: [
      "Grande cratera Odysseus (400 km)",
      "Sistema de vales Ithaca Chasma",
      "Sempre mostra a mesma face para Saturno",
      "Tem duas pequenas luas troianas"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#C0C0C0",
    composition: "Gelo de água com pequeno núcleo rochoso",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.80,
    parent_planet: "saturn"
  },
  {
    id: "moon-14",
    name: "mimas",
    portuguese_name: "Mimas",
    radius: 198.2,
    mass: 3.75e19,
    gravity: 0.064,
    average_temperature: -200,
    distance_from_planet: 185404,
    orbital_period: 0.94,
    rotation_period: 0.94,
    description: "Lua de Saturno conhecida por sua grande cratera que a faz parecer com a Estrela da Morte.",
    curiosities: [
      "Cratera Herschel (130 km) - 1/3 do diâmetro",
      "Parece com a Estrela da Morte de Star Wars",
      "Sempre mostra a mesma face para Saturno",
      "Uma das menores luas esféricas conhecidas"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA12570/PIA12570~orig.jpg",
    color: "#C0C0C0",
    composition: "Gelo de água com pequeno núcleo rochoso",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.50,
    parent_planet: "saturn"
  },
  {
    id: "moon-15",
    name: "hyperion",
    portuguese_name: "Hiperião",
    radius: 135,
    mass: 5.62e18,
    gravity: 0.020,
    average_temperature: -180,
    distance_from_planet: 1481010,
    orbital_period: 21.28,
    rotation_period: 13.05,
    description: "Lua de Saturno com formato irregular e rotação caótica.",
    curiosities: [
      "Formato irregular (batata)",
      "Rotação caótica e imprevisível",
      "Superfície esponjosa e porosa",
      "Uma das luas mais distantes de Saturno"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.30,
    parent_planet: "saturn"
  },
  {
    id: "moon-16",
    name: "phoebe",
    portuguese_name: "Febe",
    radius: 106.5,
    mass: 8.29e18,
    gravity: 0.049,
    average_temperature: -198,
    distance_from_planet: 12944400,
    orbital_period: 550.48,
    rotation_period: 0.39,
    description: "Lua de Saturno com órbita retrógrada e superfície escura.",
    curiosities: [
      "Órbita retrógrada (gira no sentido contrário)",
      "Superfície escura e craterada",
      "Possível origem em objetos do Cinturão de Kuiper",
      "Fonte de material para os anéis de Saturno"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#2F2F2F",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.06,
    parent_planet: "saturn"
  },
  {
    id: "moon-17",
    name: "pan",
    portuguese_name: "Pan",
    radius: 14.1,
    mass: 4.95e15,
    gravity: 0.001,
    average_temperature: -198,
    distance_from_planet: 133584,
    orbital_period: 0.58,
    rotation_period: 0.58,
    description: "Lua pastor de Saturno que mantém a Divisão de Encke nos anéis.",
    curiosities: [
      "Lua pastor que mantém a Divisão de Encke",
      "Formato de noz devido à rotação rápida",
      "Uma das menores luas de Saturno",
      "Órbita dentro dos anéis principais"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.50,
    parent_planet: "saturn"
  },
  {
    id: "moon-18",
    name: "atlas",
    portuguese_name: "Atlas",
    radius: 15.1,
    mass: 6.6e15,
    gravity: 0.001,
    average_temperature: -198,
    distance_from_planet: 137670,
    orbital_period: 0.60,
    rotation_period: 0.60,
    description: "Lua pastor de Saturno que mantém o anel A.",
    curiosities: [
      "Lua pastor do anel A",
      "Formato de disco devido à rotação",
      "Órbita próxima aos anéis",
      "Descoberta em 1980"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.50,
    parent_planet: "saturn"
  },
  {
    id: "moon-19",
    name: "prometheus",
    portuguese_name: "Prometeu",
    radius: 43.1,
    mass: 1.6e17,
    gravity: 0.006,
    average_temperature: -198,
    distance_from_planet: 139380,
    orbital_period: 0.61,
    rotation_period: 0.61,
    description: "Lua pastor de Saturno que mantém o anel F.",
    curiosities: [
      "Lua pastor do anel F",
      "Órbita caótica e irregular",
      "Interage com o anel F criando estruturas",
      "Descoberta em 1980"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.60,
    parent_planet: "saturn"
  },
  {
    id: "moon-20",
    name: "pandora",
    portuguese_name: "Pandora",
    radius: 40.7,
    mass: 1.4e17,
    gravity: 0.005,
    average_temperature: -198,
    distance_from_planet: 141720,
    orbital_period: 0.63,
    rotation_period: 0.63,
    description: "Lua pastor de Saturno que mantém o anel F junto com Prometeu.",
    curiosities: [
      "Lua pastor do anel F",
      "Trabalha em conjunto com Prometeu",
      "Órbita caótica e irregular",
      "Descoberta em 1980"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.60,
    parent_planet: "saturn"
  },
  {
    id: "moon-21",
    name: "janus",
    portuguese_name: "Janus",
    radius: 89.5,
    mass: 1.9e18,
    gravity: 0.016,
    average_temperature: -198,
    distance_from_planet: 151460,
    orbital_period: 0.70,
    rotation_period: 0.70,
    description: "Lua de Saturno que troca de órbita com Epimeteu a cada 4 anos.",
    curiosities: [
      "Troca de órbita com Epimeteu",
      "Órbitas co-orbitais únicas",
      "Sempre mostra a mesma face para Saturno",
      "Descoberta em 1966"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#C0C0C0",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.60,
    parent_planet: "saturn"
  },
  {
    id: "moon-22",
    name: "epimetheus",
    portuguese_name: "Epimeteu",
    radius: 58.1,
    mass: 5.3e17,
    gravity: 0.010,
    average_temperature: -198,
    distance_from_planet: 151410,
    orbital_period: 0.69,
    rotation_period: 0.69,
    description: "Lua de Saturno que troca de órbita com Janus a cada 4 anos.",
    curiosities: [
      "Troca de órbita com Janus",
      "Órbitas co-orbitais únicas",
      "Sempre mostra a mesma face para Saturno",
      "Descoberta em 1966"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#C0C0C0",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.60,
    parent_planet: "saturn"
  },
  {
    id: "moon-23",
    name: "helene",
    portuguese_name: "Helena",
    radius: 17.6,
    mass: 1.1e16,
    gravity: 0.0004,
    average_temperature: -198,
    distance_from_planet: 377396,
    orbital_period: 2.74,
    rotation_period: 2.74,
    description: "Lua troiana de Tétis, compartilhando a mesma órbita.",
    curiosities: [
      "Lua troiana de Tétis",
      "Compartilha órbita com Tétis",
      "Sempre mostra a mesma face para Saturno",
      "Descoberta em 1980"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#C0C0C0",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.60,
    parent_planet: "saturn"
  },
  {
    id: "moon-24",
    name: "telesto",
    portuguese_name: "Telesto",
    radius: 12.4,
    mass: 3.9e15,
    gravity: 0.0002,
    average_temperature: -198,
    distance_from_planet: 294619,
    orbital_period: 1.89,
    rotation_period: 1.89,
    description: "Lua troiana de Tétis, orbitando no ponto L4.",
    curiosities: [
      "Lua troiana de Tétis",
      "Órbita no ponto L4 de Lagrange",
      "Sempre mostra a mesma face para Saturno",
      "Descoberta em 1980"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#C0C0C0",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.60,
    parent_planet: "saturn"
  },
  {
    id: "moon-25",
    name: "calypso",
    portuguese_name: "Calipso",
    radius: 10.7,
    mass: 2.5e15,
    gravity: 0.0001,
    average_temperature: -198,
    distance_from_planet: 294619,
    orbital_period: 1.89,
    rotation_period: 1.89,
    description: "Lua troiana de Tétis, orbitando no ponto L5.",
    curiosities: [
      "Lua troiana de Tétis",
      "Órbita no ponto L5 de Lagrange",
      "Sempre mostra a mesma face para Saturno",
      "Descoberta em 1980"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#C0C0C0",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.60,
    parent_planet: "saturn"
  },
  {
    id: "moon-26",
    name: "polydeuces",
    portuguese_name: "Polideuces",
    radius: 1.3,
    mass: 1.0e13,
    gravity: 0.00001,
    average_temperature: -198,
    distance_from_planet: 377396,
    orbital_period: 2.74,
    rotation_period: 2.74,
    description: "Lua troiana de Dione, uma das menores luas de Saturno.",
    curiosities: [
      "Lua troiana de Dione",
      "Uma das menores luas de Saturno",
      "Órbita instável",
      "Descoberta em 2004"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.50,
    parent_planet: "saturn"
  },
  {
    id: "moon-27",
    name: "methone",
    portuguese_name: "Metone",
    radius: 1.6,
    mass: 1.5e13,
    gravity: 0.00001,
    average_temperature: -198,
    distance_from_planet: 194440,
    orbital_period: 1.01,
    rotation_period: 1.01,
    description: "Pequena lua de Saturno com formato elipsoidal.",
    curiosities: [
      "Formato elipsoidal",
      "Órbita próxima aos anéis",
      "Sempre mostra a mesma face para Saturno",
      "Descoberta em 2004"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.50,
    parent_planet: "saturn"
  },
  {
    id: "moon-28",
    name: "pallene",
    portuguese_name: "Palene",
    radius: 2.2,
    mass: 3.5e13,
    gravity: 0.00001,
    average_temperature: -198,
    distance_from_planet: 212280,
    orbital_period: 1.15,
    rotation_period: 1.15,
    description: "Pequena lua de Saturno com anel de poeira.",
    curiosities: [
      "Possui anel de poeira próprio",
      "Órbita próxima aos anéis",
      "Sempre mostra a mesma face para Saturno",
      "Descoberta em 2004"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.50,
    parent_planet: "saturn"
  },
  {
    id: "moon-29",
    name: "anthe",
    portuguese_name: "Ante",
    radius: 0.9,
    mass: 5.0e12,
    gravity: 0.000005,
    average_temperature: -198,
    distance_from_planet: 197700,
    orbital_period: 1.04,
    rotation_period: 1.04,
    description: "Uma das menores luas de Saturno.",
    curiosities: [
      "Uma das menores luas de Saturno",
      "Órbita próxima aos anéis",
      "Sempre mostra a mesma face para Saturno",
      "Descoberta em 2007"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.50,
    parent_planet: "saturn"
  },
  {
    id: "moon-30",
    name: "aegaeon",
    portuguese_name: "Egeão",
    radius: 0.3,
    mass: 1.0e11,
    gravity: 0.000001,
    average_temperature: -198,
    distance_from_planet: 167500,
    orbital_period: 0.81,
    rotation_period: 0.81,
    description: "A menor lua de Saturno, mantém o anel G.",
    curiosities: [
      "A menor lua de Saturno",
      "Mantém o anel G",
      "Órbita dentro dos anéis",
      "Descoberta em 2008"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.50,
    parent_planet: "saturn"
  },
  {
    id: "moon-67",
    name: "daphnis",
    portuguese_name: "Dafne",
    radius: 3.8,
    mass: 7.7e13,
    gravity: 0.0001,
    average_temperature: -198,
    distance_from_planet: 136505,
    orbital_period: 0.59,
    rotation_period: 0.59,
    description: "Lua pastor de Saturno que mantém a Divisão de Keeler.",
    curiosities: [
      "Lua pastor da Divisão de Keeler",
      "Órbita próxima aos anéis",
      "Sempre mostra a mesma face para Saturno",
      "Descoberta em 2005"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.50,
    parent_planet: "saturn"
  },
  {
    id: "moon-68",
    name: "polydeuces",
    portuguese_name: "Polideuces",
    radius: 1.3,
    mass: 1.0e13,
    gravity: 0.00001,
    average_temperature: -198,
    distance_from_planet: 377396,
    orbital_period: 2.74,
    rotation_period: 2.74,
    description: "Lua troiana de Dione, uma das menores luas de Saturno.",
    curiosities: [
      "Lua troiana de Dione",
      "Uma das menores luas de Saturno",
      "Órbita instável",
      "Descoberta em 2004"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.50,
    parent_planet: "saturn"
  },
  {
    id: "moon-69",
    name: "kiviuq",
    portuguese_name: "Kiviuq",
    radius: 8,
    mass: 3.3e15,
    gravity: 0.0001,
    average_temperature: -198,
    distance_from_planet: 11310000,
    orbital_period: 449.22,
    rotation_period: 7.78,
    description: "Lua irregular de Saturno com órbita próxima.",
    curiosities: [
      "Órbita próxima",
      "Formato irregular",
      "Possível origem em asteroide capturado",
      "Descoberta em 2000"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "saturn"
  },
  {
    id: "moon-70",
    name: "ijiraq",
    portuguese_name: "Ijiraq",
    radius: 6,
    mass: 1.2e15,
    gravity: 0.0001,
    average_temperature: -198,
    distance_from_planet: 11124000,
    orbital_period: 451.46,
    rotation_period: 7.78,
    description: "Lua irregular de Saturno com órbita próxima.",
    curiosities: [
      "Órbita próxima",
      "Formato irregular",
      "Possível origem em asteroide capturado",
      "Descoberta em 2000"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "saturn"
  },
  {
    id: "moon-71",
    name: "paaliaq",
    portuguese_name: "Paaliaq",
    radius: 11,
    mass: 8.2e15,
    gravity: 0.0001,
    average_temperature: -198,
    distance_from_planet: 15200000,
    orbital_period: 686.95,
    rotation_period: 7.78,
    description: "Lua irregular de Saturno com órbita distante.",
    curiosities: [
      "Órbita distante",
      "Formato irregular",
      "Possível origem em asteroide capturado",
      "Descoberta em 2000"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "saturn"
  },
  {
    id: "moon-72",
    name: "tarqeq",
    portuguese_name: "Tarqeq",
    radius: 3.5,
    mass: 1.8e14,
    gravity: 0.00001,
    average_temperature: -198,
    distance_from_planet: 17946000,
    orbital_period: 894.86,
    rotation_period: 7.78,
    description: "Lua irregular de Saturno com órbita distante.",
    curiosities: [
      "Órbita distante",
      "Formato irregular",
      "Possível origem em asteroide capturado",
      "Descoberta em 2007"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "saturn"
  },
  {
    id: "moon-73",
    name: "siarnaq",
    portuguese_name: "Siarnaq",
    radius: 20,
    mass: 3.9e16,
    gravity: 0.0001,
    average_temperature: -198,
    distance_from_planet: 17965000,
    orbital_period: 895.53,
    rotation_period: 7.78,
    description: "Lua irregular de Saturno com órbita distante.",
    curiosities: [
      "Órbita distante",
      "Formato irregular",
      "Possível origem em asteroide capturado",
      "Descoberta em 2000"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "saturn"
  },
  {
    id: "moon-74",
    name: "tarvos",
    portuguese_name: "Tarvos",
    radius: 7.5,
    mass: 1.3e15,
    gravity: 0.0001,
    average_temperature: -198,
    distance_from_planet: 17946000,
    orbital_period: 926.19,
    rotation_period: 7.78,
    description: "Lua irregular de Saturno com órbita distante.",
    curiosities: [
      "Órbita distante",
      "Formato irregular",
      "Possível origem em asteroide capturado",
      "Descoberta em 2000"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "saturn"
  },
  {
    id: "moon-75",
    name: "hyrrokkin",
    portuguese_name: "Hyrrokkin",
    radius: 4,
    mass: 3.4e14,
    gravity: 0.00001,
    average_temperature: -198,
    distance_from_planet: 18438000,
    orbital_period: 931.86,
    rotation_period: 7.78,
    description: "Lua irregular de Saturno com órbita distante.",
    curiosities: [
      "Órbita distante",
      "Formato irregular",
      "Possível origem em asteroide capturado",
      "Descoberta em 2004"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "saturn"
  },
  {
    id: "moon-76",
    name: "greip",
    portuguese_name: "Greip",
    radius: 3,
    mass: 1.4e14,
    gravity: 0.00001,
    average_temperature: -198,
    distance_from_planet: 18438000,
    orbital_period: 906.56,
    rotation_period: 7.78,
    description: "Lua irregular de Saturno com órbita distante.",
    curiosities: [
      "Órbita distante",
      "Formato irregular",
      "Possível origem em asteroide capturado",
      "Descoberta em 2006"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "saturn"
  },
  {
    id: "moon-77",
    name: "jarnsaxa",
    portuguese_name: "Jarnsaxa",
    radius: 3,
    mass: 1.4e14,
    gravity: 0.00001,
    average_temperature: -198,
    distance_from_planet: 18438000,
    orbital_period: 964.74,
    rotation_period: 7.78,
    description: "Lua irregular de Saturno com órbita distante.",
    curiosities: [
      "Órbita distante",
      "Formato irregular",
      "Possível origem em asteroide capturado",
      "Descoberta em 2006"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "saturn"
  },
  // Luas de Urano
  {
    id: "moon-6",
    name: "miranda",
    portuguese_name: "Miranda",
    radius: 235.8,
    mass: 6.59e19,
    gravity: 0.079,
    average_temperature: -187,
    distance_from_planet: 129390,
    orbital_period: 1.41,
    rotation_period: 1.41,
    description: "A menor das cinco luas principais de Urano, conhecida por sua superfície extremamente variada.",
    curiosities: [
      "Superfície mais variada do Sistema Solar",
      "Possui cânions de 20 km de profundidade",
      "Sempre mostra a mesma face para Urano",
      "Foi descoberta em 1948"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA18185/PIA18185~orig.jpg",
    color: "#C0C0C0",
    composition: "Gelo de água com silicatos",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.32,
    parent_planet: "uranus"
  },
  {
    id: "moon-7",
    name: "ariel",
    portuguese_name: "Ariel",
    radius: 578.9,
    mass: 1.35e21,
    gravity: 0.269,
    average_temperature: -213,
    distance_from_planet: 191020,
    orbital_period: 2.52,
    rotation_period: 2.52,
    description: "Uma das maiores luas de Urano, com superfície jovem e sistema de vales extenso.",
    curiosities: [
      "Superfície mais jovem das luas de Urano",
      "Possui sistema de vales extenso",
      "Sempre mostra a mesma face para Urano",
      "Foi descoberta em 1851"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#C0C0C0",
    composition: "Gelo de água com silicatos",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.39,
    parent_planet: "uranus"
  },
  {
    id: "moon-31",
    name: "umbriel",
    portuguese_name: "Umbriel",
    radius: 584.7,
    mass: 1.17e21,
    gravity: 0.23,
    average_temperature: -198,
    distance_from_planet: 266000,
    orbital_period: 4.14,
    rotation_period: 4.14,
    description: "Lua de Urano com superfície escura e craterada.",
    curiosities: [
      "Superfície mais escura de Urano",
      "Pouco craterada comparada a outras luas",
      "Sempre mostra a mesma face para Urano",
      "Tem uma cratera brilhante chamada Wunda"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#2F2F2F",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.19,
    parent_planet: "uranus"
  },
  {
    id: "moon-32",
    name: "titania",
    portuguese_name: "Titânia",
    radius: 788.9,
    mass: 3.52e21,
    gravity: 0.38,
    average_temperature: -203,
    distance_from_planet: 436300,
    orbital_period: 8.71,
    rotation_period: 8.71,
    description: "A maior lua de Urano, com vales e falhas extensas.",
    curiosities: [
      "Maior lua de Urano",
      "Tem vales de 1000 km de comprimento",
      "Sempre mostra a mesma face para Urano",
      "Possível atividade geológica no passado"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#C0C0C0",
    composition: "Gelo de água com núcleo rochoso",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.27,
    parent_planet: "uranus"
  },
  {
    id: "moon-33",
    name: "oberon",
    portuguese_name: "Oberon",
    radius: 761.4,
    mass: 3.01e21,
    gravity: 0.35,
    average_temperature: -203,
    distance_from_planet: 583500,
    orbital_period: 13.46,
    rotation_period: 13.46,
    description: "A segunda maior lua de Urano, com superfície antiga e craterada.",
    curiosities: [
      "Segunda maior lua de Urano",
      "Superfície mais antiga e craterada",
      "Sempre mostra a mesma face para Urano",
      "Tem montanhas de 6 km de altura"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.24,
    parent_planet: "uranus"
  },
  {
    id: "moon-34",
    name: "cordelia",
    portuguese_name: "Cordélia",
    radius: 20.1,
    mass: 4.4e16,
    gravity: 0.007,
    average_temperature: -198,
    distance_from_planet: 49780,
    orbital_period: 0.33,
    rotation_period: 0.33,
    description: "Lua pastor de Urano, mantém o anel epsilon.",
    curiosities: [
      "Lua pastor do anel epsilon",
      "Órbita próxima aos anéis",
      "Sempre mostra a mesma face para Urano",
      "Descoberta em 1986"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.50,
    parent_planet: "uranus"
  },
  {
    id: "moon-35",
    name: "ophelia",
    portuguese_name: "Ofélia",
    radius: 21.4,
    mass: 5.4e16,
    gravity: 0.008,
    average_temperature: -198,
    distance_from_planet: 53760,
    orbital_period: 0.38,
    rotation_period: 0.38,
    description: "Lua pastor de Urano, mantém o anel epsilon junto com Cordélia.",
    curiosities: [
      "Lua pastor do anel epsilon",
      "Trabalha em conjunto com Cordélia",
      "Sempre mostra a mesma face para Urano",
      "Descoberta em 1986"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.50,
    parent_planet: "uranus"
  },
  {
    id: "moon-36",
    name: "bianca",
    portuguese_name: "Bianca",
    radius: 25.7,
    mass: 9.2e16,
    gravity: 0.009,
    average_temperature: -198,
    distance_from_planet: 59170,
    orbital_period: 0.43,
    rotation_period: 0.43,
    description: "Lua de Urano com órbita próxima aos anéis.",
    curiosities: [
      "Órbita próxima aos anéis",
      "Sempre mostra a mesma face para Urano",
      "Descoberta em 1986",
      "Uma das luas internas de Urano"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.50,
    parent_planet: "uranus"
  },
  {
    id: "moon-37",
    name: "cressida",
    portuguese_name: "Cressida",
    radius: 39.8,
    mass: 3.4e17,
    gravity: 0.014,
    average_temperature: -198,
    distance_from_planet: 61780,
    orbital_period: 0.46,
    rotation_period: 0.46,
    description: "Lua de Urano com formato irregular.",
    curiosities: [
      "Formato irregular",
      "Órbita próxima aos anéis",
      "Sempre mostra a mesma face para Urano",
      "Descoberta em 1986"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.50,
    parent_planet: "uranus"
  },
  {
    id: "moon-38",
    name: "desdemona",
    portuguese_name: "Desdêmona",
    radius: 32.0,
    mass: 1.8e17,
    gravity: 0.012,
    average_temperature: -198,
    distance_from_planet: 62660,
    orbital_period: 0.47,
    rotation_period: 0.47,
    description: "Lua de Urano com órbita instável.",
    curiosities: [
      "Órbita instável",
      "Pode colidir com outras luas",
      "Sempre mostra a mesma face para Urano",
      "Descoberta em 1986"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.50,
    parent_planet: "uranus"
  },
  {
    id: "moon-39",
    name: "juliet",
    portuguese_name: "Julieta",
    radius: 46.8,
    mass: 5.6e17,
    gravity: 0.017,
    average_temperature: -198,
    distance_from_planet: 64400,
    orbital_period: 0.49,
    rotation_period: 0.49,
    description: "Lua de Urano com formato irregular.",
    curiosities: [
      "Formato irregular",
      "Órbita próxima aos anéis",
      "Sempre mostra a mesma face para Urano",
      "Descoberta em 1986"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.50,
    parent_planet: "uranus"
  },
  {
    id: "moon-40",
    name: "portia",
    portuguese_name: "Pórcia",
    radius: 67.6,
    mass: 1.7e18,
    gravity: 0.025,
    average_temperature: -198,
    distance_from_planet: 66100,
    orbital_period: 0.51,
    rotation_period: 0.51,
    description: "Lua de Urano com formato irregular.",
    curiosities: [
      "Formato irregular",
      "Órbita próxima aos anéis",
      "Sempre mostra a mesma face para Urano",
      "Descoberta em 1986"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.50,
    parent_planet: "uranus"
  },
  // Luas de Netuno
  {
    id: "moon-8",
    name: "triton",
    portuguese_name: "Tritão",
    radius: 1353.4,
    mass: 2.14e22,
    gravity: 0.779,
    average_temperature: -235,
    distance_from_planet: 354759,
    orbital_period: -5.88,
    rotation_period: 5.88,
    description: "A maior lua de Netuno e única grande lua com órbita retrógrada no Sistema Solar.",
    curiosities: [
      "Órbita retrógrada (gira no sentido contrário)",
      "Tem gêiseres de nitrogênio",
      "Possível oceano subterrâneo",
      "Será destruída por Netuno em bilhões de anos"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA00348/PIA00348~orig.jpg",
    color: "#C0C0C0",
    composition: "Núcleo rochoso, manto de gelo, crosta de gelo de nitrogênio",
    atmosphere: "Exosfera tênue de nitrogênio",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.76,
    parent_planet: "neptune"
  },
  {
    id: "moon-9",
    name: "proteus",
    portuguese_name: "Proteu",
    radius: 210,
    mass: 5.04e19,
    gravity: 0.12,
    average_temperature: -220,
    distance_from_planet: 117647,
    orbital_period: 1.12,
    rotation_period: 1.12,
    description: "A segunda maior lua de Netuno, com formato irregular e superfície escura.",
    curiosities: [
      "Formato irregular (não esférico)",
      "Superfície escura e craterada",
      "Sempre mostra a mesma face para Netuno",
      "Foi descoberta em 1989"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA00061/PIA00061~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com silicatos",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.096,
    parent_planet: "neptune"
  },
  {
    id: "moon-41",
    name: "nereid",
    portuguese_name: "Nereida",
    radius: 170,
    mass: 3.1e19,
    gravity: 0.071,
    average_temperature: -220,
    distance_from_planet: 5513400,
    orbital_period: 360.13,
    rotation_period: 11.31,
    description: "A terceira maior lua de Netuno, com órbita muito excêntrica.",
    curiosities: [
      "Órbita mais excêntrica do Sistema Solar",
      "Período orbital de quase 1 ano terrestre",
      "Sempre mostra a mesma face para Netuno",
      "Foi descoberta em 1949"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água com material orgânico",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.16,
    parent_planet: "neptune"
  },
  {
    id: "moon-42",
    name: "larissa",
    portuguese_name: "Larissa",
    radius: 97,
    mass: 4.9e18,
    gravity: 0.021,
    average_temperature: -220,
    distance_from_planet: 73548,
    orbital_period: 0.55,
    rotation_period: 0.55,
    description: "Lua de Netuno com formato irregular e superfície escura.",
    curiosities: [
      "Formato irregular",
      "Superfície escura e craterada",
      "Sempre mostra a mesma face para Netuno",
      "Foi descoberta em 1981"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.09,
    parent_planet: "neptune"
  },
  {
    id: "moon-43",
    name: "galatea",
    portuguese_name: "Galateia",
    radius: 87.4,
    mass: 2.1e18,
    gravity: 0.018,
    average_temperature: -220,
    distance_from_planet: 61953,
    orbital_period: 0.43,
    rotation_period: 0.43,
    description: "Lua pastor de Netuno, mantém o anel Adams.",
    curiosities: [
      "Lua pastor do anel Adams",
      "Órbita próxima aos anéis",
      "Sempre mostra a mesma face para Netuno",
      "Foi descoberta em 1989"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.08,
    parent_planet: "neptune"
  },
  {
    id: "moon-44",
    name: "despina",
    portuguese_name: "Despina",
    radius: 78,
    mass: 2.1e18,
    gravity: 0.017,
    average_temperature: -220,
    distance_from_planet: 52526,
    orbital_period: 0.33,
    rotation_period: 0.33,
    description: "Lua de Netuno com formato irregular.",
    curiosities: [
      "Formato irregular",
      "Órbita próxima aos anéis",
      "Sempre mostra a mesma face para Netuno",
      "Foi descoberta em 1989"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.09,
    parent_planet: "neptune"
  },
  {
    id: "moon-45",
    name: "thalassa",
    portuguese_name: "Talassa",
    radius: 40.7,
    mass: 3.5e17,
    gravity: 0.007,
    average_temperature: -220,
    distance_from_planet: 50075,
    orbital_period: 0.31,
    rotation_period: 0.31,
    description: "Lua de Netuno com formato irregular.",
    curiosities: [
      "Formato irregular",
      "Órbita próxima aos anéis",
      "Sempre mostra a mesma face para Netuno",
      "Foi descoberta em 1989"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.09,
    parent_planet: "neptune"
  },
  {
    id: "moon-46",
    name: "naiad",
    portuguese_name: "Náiade",
    radius: 29.6,
    mass: 1.9e17,
    gravity: 0.005,
    average_temperature: -220,
    distance_from_planet: 48227,
    orbital_period: 0.29,
    rotation_period: 0.29,
    description: "A lua mais próxima de Netuno.",
    curiosities: [
      "Lua mais próxima de Netuno",
      "Órbita próxima aos anéis",
      "Sempre mostra a mesma face para Netuno",
      "Foi descoberta em 1989"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.07,
    parent_planet: "neptune"
  },
  {
    id: "moon-47",
    name: "halimede",
    portuguese_name: "Halimede",
    radius: 31,
    mass: 9.0e16,
    gravity: 0.004,
    average_temperature: -220,
    distance_from_planet: 16611000,
    orbital_period: 1879.71,
    rotation_period: 11.31,
    description: "Lua irregular de Netuno com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita muito distante de Netuno",
      "Possível origem em Tritão",
      "Foi descoberta em 2002"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "neptune"
  },
  {
    id: "moon-48",
    name: "psamathe",
    portuguese_name: "Psâmate",
    radius: 20,
    mass: 1.5e16,
    gravity: 0.002,
    average_temperature: -220,
    distance_from_planet: 46695000,
    orbital_period: 9115.9,
    rotation_period: 11.31,
    description: "Lua irregular de Netuno com órbita retrógrada.",
    curiosities: [
      "Órbita retrógrada",
      "Órbita mais distante de Netuno",
      "Possível origem em Tritão",
      "Foi descoberta em 2003"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "neptune"
  },
  {
    id: "moon-49",
    name: "sao",
    portuguese_name: "Sao",
    radius: 22,
    mass: 2.3e16,
    gravity: 0.003,
    average_temperature: -220,
    distance_from_planet: 22228000,
    orbital_period: 2912.72,
    rotation_period: 11.31,
    description: "Lua irregular de Netuno com órbita próxima.",
    curiosities: [
      "Órbita próxima",
      "Formato irregular",
      "Possível origem em Tritão",
      "Foi descoberta em 2002"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "neptune"
  },
  {
    id: "moon-50",
    name: "laomedeia",
    portuguese_name: "Laomedeia",
    radius: 21,
    mass: 1.8e16,
    gravity: 0.003,
    average_temperature: -220,
    distance_from_planet: 23571000,
    orbital_period: 3171.33,
    rotation_period: 11.31,
    description: "Lua irregular de Netuno com órbita próxima.",
    curiosities: [
      "Órbita próxima",
      "Formato irregular",
      "Possível origem em Tritão",
      "Foi descoberta em 2002"
    ],
    image_url: "https://images-assets.nasa.gov/image/PIA07784/PIA07784~orig.jpg",
    color: "#8B7355",
    composition: "Gelo de água",
    atmosphere: "Sem atmosfera",
    magnetic_field: false,
    axial_tilt: 0,
    albedo: 0.04,
    parent_planet: "neptune"
  }
]

// Função para obter todas as luas
export function getAllMoons(): Moon[] {
  return FIXED_MOONS
}

// Função para obter luas de um planeta específico
export function getMoonsByPlanet(planetName: string): Moon[] {
  return FIXED_MOONS.filter(moon => moon.parent_planet === planetName.toLowerCase())
}

// Função para obter todos os planetas
export function getAllPlanets(): Planet[] {
  return FIXED_PLANETS
}
